### ISSUE TITLE
What's anchors/target mean ? I got  anchors/target = 3.83

### ISSUE THREAD

**Issue by ShirleyHe2020** [yl305237731/flexible-yolov5#10]
Analyzing anchors... anchors/target = 3.83, Best Possible Recall (BPR) = 0.9878
Image sizes 640 train, 640 test
Using 8 dataloader workers
Logging results to runs/train/exp7

**Comment by yl305237731** [comment]
@ShirleyHe2020    https://github.com/ultralytics/yolov5/issues/1846#issuecomment-754778379
