### ISSUE TITLE
What's depth gain ? width gain?  Can anyone tell why the values in gains are  .0.33, 0.5,,,,1.33, 1.25 ?  

### ISSUE THREAD

**Issue by ShirleyHe2020** [yl305237731/flexible-yolov5#13]
class YOLOv5(nn.Module):
    def __init__(self, focus=True, version='L'):
        super(YOLOv5, self).__init__()
        self.version = version
        self.with_focus = focus

        gains = {'s': {'gd': 0.33, 'gw': 0.5},
                 'm': {'gd': 0.67, 'gw': 0.75},
                 'l': {'gd': 1, 'gw': 1},
                 'x': {'gd': 1.33, 'gw': 1.25}}
        self.gd = gains[self.version.lower()]['gd']  # depth gain
        self.gw = gains[self.version.lower()]['gw']  # width gain

what's # depth gain , # width gain ?

**Comment by yl305237731** [comment]
it's hard to explain, you should ask the author of origin yolov5......

**Comment by yl305237731** [comment]
the width gain and depth gain control layer's depth and width
