### ISSUE TITLE
Why the mAP(0.06) so low?  Same dataset, same batch-size, when trained with ultralytics/yolov5, mAP is 0.90 within less than 200 epochs.

### ISSUE THREAD

**Issue by ShirleyHe2020** [yl305237731/flexible-yolov5#16]
![image](https://user-images.githubusercontent.com/63453957/115166022-9d2e2700-a0e3-11eb-8934-4ae5824caa4a.png)

**Comment by ShirleyHe2020** [comment]
Don't know if anything I need to be notified of before training with code in this repo....

**Comment by yl305237731** [comment]
@ShirleyHe2020 can you tell me which backbone ? I will verify it.

**Comment by Zpadger** [comment]
@yl305237731 I also encountered the same problem, using EfficientNet：
`python ./scripts/train.py --img 640 --batch 4 --epoch 10 --data ./data/color_class.yaml --cfg ./configs/model_efficientnet.yaml`～

**Comment by yl305237731** [comment]
> @yl305237731 I also encountered the same problem, using EfficientNet：
> `python ./scripts/train.py --img 640 --batch 4 --epoch 10 --data ./data/color_class.yaml --cfg ./configs/model_efficientnet.yaml`～

@Zpadger 😳，OK ，i will try this backbone.

**Comment by Zpadger** [comment]
@yl305237731 I just located the problem, and it seems I know the reason, I forgot to change the classes in the model_efficient.yaml file，so the "nc" is still "nc : 1".I have corrected the value now, and I am going to continue to run the experiment and wait for tomorrow to verify the result.

**Comment by yl305237731** [comment]
@Zpadger i have try efficientnet B2 as backbone, it's no problem.

**Comment by yl305237731** [comment]
> Don't know if anything I need to be notified of before training with code in this repo....

@ShirleyHe2020 hi, may be your problem is same as @Zpadger , so check nc in model_XXXX.yaml.

**Comment by Zpadger** [comment]
@yl305237731 I got up in the morning and looked at the training results. There is no problem with the EfficientNet model. At present, the mAP of Epoch35/49 has reached 0.982. Thank you for your contribution.

**Comment by ShirleyHe2020** [comment]
> @ShirleyHe2020 can you tell me which backbone ? I will verify it
-----------------------------------------------------
from my side, all the backbones ( mobilenet, efficientnet, reset ) suffer the same issue.

**Comment by yl305237731** [comment]
@ShirleyHe2020 i think you forget to change the nc to your dataset in model_xxx.yaml

**Comment by ShirleyHe2020** [comment]
> > Don't know if anything I need to be notified of before training with code in this repo....
> 
> @ShirleyHe2020 hi, may be your problem is same as @Zpadger , so check nc in model_XXXX.yaml.

thanks  @Zpadger , same issue , 'nc' changed then mAP reached expected level

**Comment by Lg955** [comment]
Hi @ShirleyHe2020 @Zpadger Where to load the efficientnet weights when using the B6 as backbone? It does not remind me to download weights or load it.

**Comment by yl305237731** [comment]
@Lg955 hi, i have try b6, there is no problem
![image](https://user-images.githubusercontent.com/9928596/116769728-ed58a200-aa70-11eb-941e-a3387c1107a1.png)

**Comment by Lg955** [comment]
@yl305237731  My showing of result is different from yours:
![loader](https://user-images.githubusercontent.com/69025725/116770024-1b3ee600-aa73-11eb-90d3-67dd1bffb52e.png)


And the .yaml is this:
`backbone:
  type: efficientnet
  version: b2 # b1 to b8 and l2
head:
  nc: 5
  stride: [8.0, 16.0, 32.0]
  anchors:
    - [10,13, 16,30, 33,23]  # P3/8
    - [30,61, 62,45, 59,119]  # P4/16
    - [116,90, 156,198, 373,326]  # P5/32`

**Comment by yl305237731** [comment]
@Lg955 for above information, I can't see the problem. and i test b2, there is no problem

**Comment by Lg955** [comment]
Hi， @yl305237731  when detect imgs, the pred result is empty after NMS(pred result is OK before NMS), have you encountered the same problem?

`pred before NMS tensor([[[7.02863e+00, 4.92409e+00, 2.66565e+01,  ..., 3.92634e-02, 1.15775e-01, 2.56261e-03],
         [1.08675e+01, 4.00093e+00, 3.37639e+01,  ..., 4.27754e-02, 8.12325e-02, 4.94392e-03],
         [1.85410e+01, 3.28052e+00, 3.73997e+01,  ..., 5.11962e-02, 1.00191e-01, 5.55359e-03],
         ...,
         [1.20430e+03, 7.04980e+02, 2.17258e+02,  ..., 3.21729e-02, 2.10942e-01, 8.92933e-02],
         [1.22968e+03, 7.08009e+02, 2.33180e+02,  ..., 4.42553e-02, 2.42864e-01, 1.20849e-01],
         [1.25142e+03, 7.13127e+02, 1.60746e+02,  ..., 3.88758e-02, 1.66492e-01, 1.16945e-01]]], device='cuda:0')

/------------------------/

pred after NMS [tensor([], device='cuda:0', size=(0, 6))]`
