### ISSUE TITLE
Hi, it's a great work!

### ISSUE THREAD

**Issue by Zigars** [yl305237731/flexible-yolov5#17]
you are not a cainiao, you are a dalao, hhhhh. I'm the most vegeteble one. :(

**Comment by Zigars** [comment]
And I have a question, if I want to load pretrained backbone, how can I config it

**Comment by yl305237731** [comment]
@Zpadger hi,i'm so sorry  💔, The whole organization structure has changed, so it is impossible to load Yolo pre trained weight at present 😭

**Comment by yl305237731** [comment]
@Zigars  😊,  

modify configs/model_resnte.yaml, add pretrained = True to load pretrained weights.

backbone:
  type: resnet
  version: 50  # 18, 34, 50, 101, 152
  dcn: False
  cbam: False
  pretrained: True

**Comment by Zpadger** [comment]
@yl305237731 Ok got it, thank you for your explanation.
