### ISSUE TITLE
Any interests in exploring methods to deal with Class Imbalanced (Long-tail) detection? 

### ISSUE THREAD

**Issue by ShirleyHe2020** [yl305237731/flexible-yolov5#18]
This CVPR 2020 paper claimed that Balanced Group Softmax help address class-imbalance issue , I am not sure if the methods in this paper can be combined with yolov5 ( like replaced the heads )

https://openaccess.thecvf.com/content_CVPR_2020/papers/Li_Overcoming_Classifier_Imbalance_for_Long-Tail_Object_Detection_With_Balanced_Group_CVPR_2020_paper.pdf

**Comment by yl305237731** [comment]
sorry, i dont have time to do it.

**Comment by yunbosong** [comment]
> sorry, i dont have time to do it.

why ?
time is like water in haimian.
