### ISSUE TITLE
Any interests in applying transformer in this repo ?  

### ISSUE THREAD

**Issue by ShirleyHe2020** [yl305237731/flexible-yolov5#19]
Glad to see this repo has 15 stars now, I guess it will enjoy a boom in star numbers if SOTA transformer added . :)

**Comment by yl305237731** [comment]
@ShirleyHe2020 O(∩_∩)O，ok, maybe i will add transformer in later, I'm preparing for an interview recently

**Comment by yl305237731** [comment]
@ShirleyHe2020 I took a glance at origin yolov5  hub/yolov5s_transformer.yaml, It's easy to implement. You just need to replace one layer. You can try it.

**Comment by yl305237731** [comment]
@ShirleyHe2020 transformer updated，in configs/model_yolo.yaml, with_C3TR: True

**Comment by Lg955** [comment]
> @ShirleyHe2020 transformer updated，in configs/model_yolo.yaml, with_C3TR: True

How many points improved with C3TR?

**Comment by yl305237731** [comment]
@Lg955 O(∩_∩)O, I only make sure it's work, I haven't compared it, you can do this

**Comment by Lg955** [comment]
> @Lg955 O(∩_∩)O, I only make sure it's work, I haven't compared it, you can do this

But first I can not find the path_code to load the efficientnet.pt

**Comment by ShirleyHe2020** [comment]
> @ShirleyHe2020 O(∩_∩)O，ok, maybe i will add transformer in later, I'm preparing for an interview recently

Good luck :) 🥇

**Comment by ShirleyHe2020** [comment]
> @ShirleyHe2020 transformer updated，in configs/model_yolo.yaml, with_C3TR: True

Tried with C3TR , then got error message as below : 
  model_config = yaml.load(open(model_config, 'r'))
Traceback (most recent call last):
  File "train.py", line 527, in <module>
    train(hyp, opt, device, tb_writer, wandb)
  File "train.py", line 87, in train
    model = Model(opt.cfg).to(device)  # create
  File "/home/user/anaconda3/envs/ultra_YOLOv5/flexible-yolov5-main/od/models/model.py", line 25, in __init__
    self.backbone = build_backbone(backbone_type, **model_config.backbone)
  File "/home/user/anaconda3/envs/ultra_YOLOv5/flexible-yolov5-main/od/models/backbone/__init__.py", line 16, in build_backbone
    backbone = eval(backbone_name)(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'with_C3TR'

**Comment by ShirleyHe2020** [comment]
> @ShirleyHe2020 transformer updated，in configs/model_yolo.yaml, with_C3TR: True

Got Runtime Error: CUDA error : unspecified launch failure when trained at 71/299 epochs
screenshot as below
![image](https://user-images.githubusercontent.com/63453957/116953047-d3140380-acbe-11eb-8a45-1ccaadb689ba.png)
