### ISSUE TITLE
预训练权重

### ISSUE THREAD

**Issue by Lg955** [yl305237731/flexible-yolov5#20]
训练有预训练权重吗？还是说训练的时候随机初始化？

**Comment by yl305237731** [comment]
@Lg955 resnet系列和有几个backbone可以下载预训练权重，但是只是backbone的预训练权重，别的都是随机初始化。YOLOv5的训练代码收敛很快，没有预训练权重也没有太大影响，基本上几十轮就能达到很高的召回率、准确率了

**Comment by Lg955** [comment]
好的，谢谢你

**Comment by Lg955** [comment]
yolov5新出来了yolov5x6，大佬试过在这个上面改backbone吗

**Comment by yl305237731** [comment]
我这个因为要支持别的backbone，所以标准的只能从C3,C4,C5进行特征提取. 加C2,C6啊都可以，但是需要单独实现. @Lg955

**Comment by Lg955** [comment]
> 我这个因为要支持别的backbone，所以标准的只能从C3,C4,C5进行特征提取. 加C2,C6啊都可以，但是需要单独实现. @Lg955

ok

**Comment by Lg955** [comment]
> @Lg955 resnet系列和有几个backbone可以下载预训练权重，但是只是backbone的预训练权重，别的都是随机初始化。YOLOv5的训练代码收敛很快，没有预训练权重也没有太大影响，基本上几十轮就能达到很高的召回率、准确率了
使用efficientnet-B6的时候并没有提示要下载B6的预训练权重啊，B6是随机初始化吗

**Comment by yl305237731** [comment]
@Lg955 不应该啊，代码里面有b0 到b8的权重链接，你服务器挺好啊，B6都能训，太大了，O(∩_∩)O哈哈~

**Comment by Lg955** [comment]
我把 /efficientnet/model.py中 `def efficientnet(pretrained=False, **kwargs)`改为 `def efficientnet(pretrained=True, **kwargs)`后终于可以下载预训练权重了，但是又报错` File "./od/models/backbone/efficientnet/utils.py", line 609, in load_pretrained_weights
    assert not ret.unexpected_keys, 'Missing keys when loading pretrained weights: {}'.format(ret.unexpected_keys)
AssertionError: Missing keys when loading pretrained weights: ['_fc.weight', '_fc.bias']`，我太难了，请问这个怎么解决啊，我又不敢大动代码

**Comment by a227799770055** [comment]
> @Lg955 resnet系列和有几个backbone可以下载预训练权重，但是只是backbone的预训练权重，别的都是随机初始化。YOLOv5的训练代码收敛很快，没有预训练权重也没有太大影响，基本上几十轮就能达到很高的召回率、准确率了

@yl305237731 想要请问可以只下载 backbone 的预训练权重带入作者的model 进行训练吗？

**Comment by yl305237731** [comment]
@a227799770055 得去作者的仓库去改，我这个不行
