### ISSUE TITLE
how to show the name of class in labels.jpg?

### ISSUE THREAD

**Issue by ShirleyHe2020** [yl305237731/flexible-yolov5#22]
As the image shows, the upper-left bar chart,  wanna calss name  other than ' 0 ,2, 4, 6 ' in x axis. How? 
![image](https://user-images.githubusercontent.com/63453957/118108722-ecc9ef00-b412-11eb-9a50-8be7263d14ba.png)

**Comment by yl305237731** [comment]
sorry，I didn't look at this piece of code. but i think the x axis numer is your class index of names=['babababa] in data.yaml
