### ISSUE TITLE
模型保存问题

### ISSUE THREAD

**Issue by nobody-cheng** [yl305237731/flexible-yolov5#29]
hi，训练好的模型保存下来的用netron软件看不到网络结构，这个好像只保存了参数
![image](https://user-images.githubusercontent.com/34908468/121161028-2e698080-c87f-11eb-9781-b59fce813001.png)

修改了代码按照原版的保存模型，结果还是一样，请问是我哪里错了吗
![image](https://user-images.githubusercontent.com/34908468/121161239-5fe24c00-c87f-11eb-92d4-3dfbcee83435.png)

**Comment by yl305237731** [comment]
@nobody-cheng hi, 我一直没有直接可视化过pt， 建议export onnx 一下, 我也一直用的onnx的模型呢

**Comment by nobody-cheng** [comment]
> @nobody-cheng hi, 我一直没有直接可视化过pt， 建议export onnx 一下, 我也一直用的onnx的模型呢
onnx可以可视化
谢谢
