### ISSUE TITLE
加载YOLOv5预训练模型失败

### ISSUE THREAD

**Issue by MatchX** [yl305237731/flexible-yolov5#3]
提示 ModuleNotFoundError: No module named 'models'

**Comment by MatchX** [comment]
提示 ModuleNotFoundError: No module named 'models'

**Comment by yl305237731** [comment]
@MatchX ，因为模型结构已经重构了，所以暂时不能加载原作者的预训练模型，只能从新训练，我之后完善一下

**Comment by yl305237731** [comment]
@MatchX 你好，由于加载原作者的权重时，pytorch需要反序列化去寻找原始的py文件。而重构后文件组织、文件名都变了，所以无法反序列化，所以暂时无法加载预训练权重。原作者的这个训练框架收敛很快，因此我都没有使用预训练权重。
