### ISSUE TITLE
大佬，请帮个忙

### ISSUE THREAD

**Issue by yang-gis** [yl305237731/flexible-yolov5#32]
您好，我想使用vggrep网络作为backbone，请问大佬我该修改哪些？

**Comment by yl305237731** [comment]
@yang-gis 在backbone里面加个文件进行，标准是只能三层结构的backbone

**Comment by yl305237731** [comment]
self.out_shape = {'C3_size': num_features[-3],
                          'C4_size': num_features[-2],
                          'C5_size': num_features[-1]}

加上这个字典，对应每一层输出的channel
