### ISSUE TITLE
Comparing speed of MobileNet and Yolov5_small

### ISSUE THREAD

**Issue by Mkarami3** [yl305237731/flexible-yolov5#35]
Hello
Thanks for sharing your great work.
I compared the speed of Mobilnet_small with YoloV5_small.  I noticed that MobileNet is considerably slower than YoloV5_Small.
Is it normal? I was expecting to obtain a higher speed out of MobileNet in comparison to YoloV5
Thanks

**Comment by yl305237731** [comment]
for  other backbone, the default setting of neck  is same as yolo5_L, I think that may be the reason, you can change 'version=S' in FPN, PAN  @Mkarami3

**Comment by yl305237731** [comment]
@Mkarami3 

yolov5_s:

![image](https://user-images.githubusercontent.com/9928596/126318703-281c9437-16d2-41bd-be5b-e9451468f151.png)

mobilenet_small:
![image](https://user-images.githubusercontent.com/9928596/126318745-38f1d0d5-7657-4196-8fd9-aad8a0666469.png)

I set FPN and PAN channel of same as yolov5_s.  you can set :

self.gw = 0.5
self.gd  = 0.33

in __init__ of. FPN.py and PAN.py
