### ISSUE TITLE
Images sizes do not match. This will causes images to be display incorrectly in the UI

### ISSUE THREAD

**Issue by fanbooo** [yl305237731/flexible-yolov5#39]
首先膜拜下大佬：
       目前我用swin transformer的backbone训练了1个epoch，报了Images sizes do not match. This will causes images to be display incorrectly in the UI 这个问题，看报错是transforer的py里面尺寸的问题，请教下有没有碰到过这个问题？
![image](https://user-images.githubusercontent.com/27717525/126329593-da867ae9-4825-4927-9ada-46b1c1fb6d24.png)

**Comment by yl305237731** [comment]
@fanbooo imagesize 这个应该没影响的，主要是runtime error 那个，README里面写了，使用trainsformer的话关掉 model.half 不能使用半精度的，代码里面测试时会使用半精度

**Comment by yl305237731** [comment]
#34

**Comment by fanbooo** [comment]
已解决，谢谢大佬

**Comment by a227799770055** [comment]
@fanbooo  @yl305237731 可否提供 pretrain weight的載點呢 謝謝！！

**Comment by yl305237731** [comment]
@a227799770055 不好意思，我并没有再在大数据集上完整训练过。只是在自己的数据集上验证能训练出来。

**Comment by a227799770055** [comment]
@yl305237731 了解 謝謝你！！

**Comment by cds221** [comment]
@Bobo-y 请问大佬，在自己数据集上验证的精度效果怎么样呢？
