### ISSUE TITLE
Can you please explain backbone, neck ,head in your repo here ? 

### ISSUE THREAD

**Issue by ShirleyHe2020** [yl305237731/flexible-yolov5#4]

**Comment by yl305237731** [comment]
the one-stage object detection network can be divide into three part {backbone: feature extraction， neck: feature aggregation, head:  prediction and regression}，image --->backbone--->neck --->head.

**Comment by ShirleyHe2020** [comment]
> the one-stage object detection network can be divide into three part {backbone: feature extraction， neck: feature aggregation, head: prediction and regression}，image --->backbone--->neck --->head. in my repo, the neck and head are fixed for now, for backbone, you are free to choose one. If you need, you can change neck or head by yourself.

Thanks for your prompt reply, I mean: How to match your code to yolov5 architecture?

**Comment by yl305237731** [comment]
choose configs/model_yolo.yaml to build yolov5 backbone, neck, and different version {s, m, l, x} mean yolov5s, yolov5m, yolov5l, yolov5x, I only support 4 yolov5  architecture.
