### ISSUE TITLE
转trt失败

### ISSUE THREAD

**Issue by xiaoerqi** [yl305237731/flexible-yolov5#44]
转trt的时候报错ERROR: INVALID_ARGUMENT: getPluginCreator could not find plugin ScatterND version 1
Completed parsing of ONNX file，麻烦问下您遇到过这个问题么

**Comment by yl305237731** [comment]
@xiaoerqi 在deploy部分已经写了这个问题了，ScatterND  不支持，导出onnx 的时候不要detection 层
