### ISSUE TITLE
backbone加载预训练模型

### ISSUE THREAD

**Issue by yongjingli** [yl305237731/flexible-yolov5#45]
请问下backbone是否可以加载预训练模型？ @yl305237731

**Comment by yl305237731** [comment]
@yongjingli 别的backbone可以，yolov5 原始的不能直接加载，有点麻烦，所以我也没弄😂

**Comment by yongjingli** [comment]
嗯嗯，其他backbone可以加载也挺好， 可以在程序里设置一下，还有提供一下权重的下载链接吗？ @yl305237731

**Comment by mei123456789** [comment]
> @yongjingli 别的backbone可以，yolov5 原始的不能直接加载，有点麻烦，所以我也没弄😂

你好，我想问一下我在别的算法的骨干resnet中添加了你写的这块可变形卷积，我给了预训练权重显示报错了，请问可以加一下你联系方式详细问你一下吗

**Comment by yl305237731** [comment]
@yongjingli 因为别人的网络没有那个模块啊，不能直接加载，加载时跳过不匹配的key

**Comment by mei123456789** [comment]
@yl305237731 请问你加了可变形卷积之后的损失换了吗

**Comment by yl305237731** [comment]
@mei123456789 不用换啊

**Comment by mei123456789** [comment]
@yl305237731 不用换的话怎么更新权重呢，我在DETR这个算法中的resnet骨干加的可变形，然后加完了，如果没有预训练权重我训了50轮了精度还是0
能否加一下你联系方式，详细问一下你，如果可以的话我QQ是2806609195；非常需要你的帮助，谢谢

**Comment by yl305237731** [comment]
@yongjingli 这个账号就是我微信号

**Comment by yl305237731** [comment]
@mei123456789 账号就是我微信号

**Comment by mei123456789** [comment]
> @mei123456789 账号就是我微信号

好的，我加你了

**Comment by mei123456789** [comment]
@yl305237731 好的，我加你了
