### ISSUE TITLE
ModuleNotFoundError: No module named 'od'

### ISSUE THREAD

**Issue by cheeenzq** [yl305237731/flexible-yolov5#46]
您好，我在调试您的代码的时候出现了ModuleNotFoundError: No module named 'od'的问题。请问怎么解决？

**Comment by yl305237731** [comment]
@cheeenzq 出现这个问题，一般是执行路径不对

**Comment by cheeenzq** [comment]
好的，非常感谢您的指导。



发自我的iPhone


------------------ Original ------------------
From: lulu ***@***.***&gt;
Date: Thu,Aug 19,2021 10:11 AM
To: yl305237731/flexible-yolov5 ***@***.***&gt;
Cc: cheeenzq ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [yl305237731/flexible-yolov5] ModuleNotFoundError: No module named 'od' (#46)





 
@cheeenzq 出现这个问题，一般是执行路径不对
