### ISSUE TITLE
怎样在网络中添加注意力机制

### ISSUE THREAD

**Issue by aidongmandexiaowowo** [yl305237731/flexible-yolov5#47]
怎样将SE,CBAM等注意力机制加入到主干网络中呢，是在backbone中修改程序吗，怎样改呢，.yaml文件需要改么
How to add SE, CBAM and other attention mechanisms to the backbone network?

**Comment by yl305237731** [comment]
yaml 基本不用改，除了resent 别的我都没有设置那个开关，关于增加SE 可以参考 backbone/mobilenetv3.py 这里面默认使用了SE，CBAM可以参考resent.py @aidongmandexiaowowo

**Comment by aidongmandexiaowowo** [comment]
谢谢，还想请问一下，如何添加sw-transformer、coord_conv、dropblock这些模块呢，能打印出网络模型结构来吗，就像yolov5原作者的那种形式，都不太懂呢，麻烦了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yl305237731/flexible-yolov5"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月31日(星期二) 下午3:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yl305237731/flexible-yolov5] 怎样在网络中添加注意力机制 (#47)





 
yaml 基本不用改，除了resent 别的我都没有设置那个开关，关于增加SE 可以参考 backbone/mobilenetv3.py 这里面默认使用了SE，CBAM可以参考resent.py @aidongmandexiaowowo
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yl305237731** [comment]
sw-transformer 已经实现了，只需要选择它的 yaml 就行了，dropblock 和 coord_conv 由于我没有验证，所以没有提供现成的集成，可以参照resent 里面的CBAM和dcn 那样就行增加，或者看看别的使用该模块的代码这么加的 @aidongmandexiaowowo

**Comment by aidongmandexiaowowo** [comment]
嗯嗯 ，好的，等着我试一下，先试一下其他实例，谢谢
