### ISSUE TITLE
swin_transformer训练时如何关闭半精度呢

### ISSUE THREAD

**Issue by aidongmandexiaowowo** [yl305237731/flexible-yolov5#49]
我还是不太明白怎样在程序中关闭半精度呢，怎样才能在train.py文件中不使用半精度呢

**Comment by yl305237731** [comment]
@aidongmandexiaowowo model.half() 注释掉

**Comment by aidongmandexiaowowo** [comment]
你好，我没有找到model.half()呢，

**Comment by aidongmandexiaowowo** [comment]
是model=attempt_load(final, device).half()吗，我把这个注释掉也不对呢，half = device.type != 'cpu'改为了half=False

**Comment by yl305237731** [comment]
@aidongmandexiaowowo 训练的时候不用用到，只有测试时才用到了，不改的话，训练也不报错啊，只有测试才报错

**Comment by aidongmandexiaowowo** [comment]
好的，我用原先的程序训练，但是显示这个错误， CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasGemmEx( handle, opa, opb, m, n, k, &falpha, a, CUDA_R_16F, lda, b, CUDA_R_16F, ldb, &fbeta, c, CUDA_R_16F, ldc, CUDA_R_32F, CUBLAS_GEMM_DFALT_TENSOR_OP)`，搜了半天也不知道怎么改呢

**Comment by yl305237731** [comment]
@aidongmandexiaowowo 这个错误没有遇到过呢，😓

**Comment by aidongmandexiaowowo** [comment]
好的，谢谢，我在看看嘞。
