### ISSUE TITLE
Question： Did you compare the metrics (mAP, F1, R, recall ) when you replaced backbone ? 

### ISSUE THREAD

**Issue by ShirleyHe2020** [yl305237731/flexible-yolov5#5]
Hi author, thanks for making this freshman-friendly repo, I noticed  'I train yolo with backbone of MobileNetV3, resnet50, shufflenet_v2_x1_0 on my dataset for person detection(27K images).' So curious about the ablation study. 

Which backbone is better for small objects?

**Comment by yl305237731** [comment]
@ShirleyHe2020 hi, i'm sorry, I didn't do a complete comparative test, I'll finish it later if I have time.

**Comment by ShirleyHe2020** [comment]
> @ShirleyHe2020 hi, i'm sorry, I didn't do a complete comparative test, I'll finish it later if I have time.

looking forward to your updates, let me be your big fan.
