### ISSUE TITLE
resnet50打开注意力机制

### ISSUE THREAD

**Issue by aidongmandexiaowowo** [yl305237731/flexible-yolov5#50]
resnet50打开注意力机制，resnet.py文件中除了打开cbam=True这一行语句，其他的不知道怎样修改呢，一直报错，好像是维度不匹配导致的。

**Comment by yl305237731** [comment]
@aidongmandexiaowowo 我看看

**Comment by aidongmandexiaowowo** [comment]
会报这个错，RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasGemmEx( handle, opa, opb, m, n, k, &falpha, a, CUDA_R_16F, lda, b, CUDA_R_16F, ldb, &fbeta,c, CUDA_R_16F, ldc, CUDA_R_32F, CUBLAS_GEMM_DFALT_TENSOR_OP)，不知道怎样修改了呢，想问你是可以直接运行的吗，麻烦了。

**Comment by yl305237731** [comment]
@aidongmandexiaowowo 之前是改个 True 或者 False 就直接跑了呢

**Comment by aidongmandexiaowowo** [comment]
好的，我自己再看一下，麻烦了。
