### ISSUE TITLE
TypeError: load() missing 1 required positional argument: 'Loader'

### ISSUE THREAD

**Issue by chennaikai11** [yl305237731/flexible-yolov5#52]
请问以下大佬，我训练自己数据集的时候为什么出现这个问题Traceback (most recent call last):
  File "scripts/train.py", line 527, in <module>
    train(hyp, opt, device, tb_writer, wandb)
  File "scripts/train.py", line 87, in train
    model = Model(opt.cfg).to(device)  # create
  File ".\od\models\model.py", line 22, in __init__
    model_config = yaml.load(open(model_config, 'r'))
TypeError: load() missing 1 required positional argument: 'Loader'

**Comment by yl305237731** [comment]
@chennaikai11 我没遇到过这个问题，可以试一下添加 yaml.load(XXX, Loader=yaml.FullLoader)

**Comment by chennaikai11** [comment]
谢谢！我已经解决了，问题是我的pyyaml版本太新了，按照您recommand上面的版本从装了yaml这个bug就自动解决了



---Original---
From: ***@***.***&gt;
Date: Sun, Oct 31, 2021 22:35 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [yl305237731/flexible-yolov5] TypeError: load() missing 1 required positional argument: 'Loader' (Issue #52)




 
@chennaikai11 我没遇到过这个问题，可以试一下添加 yaml.load(XXX, Loader=yaml.FullLoader)
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
