### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by chennaikai11** [yl305237731/flexible-yolov5#54]
运行detector.py出现这个bug，将model = Detector(pt_path, None, 416, xcycwh=False)
改为 ：namesfile= 'R:/moblie-yolov5/configs/classes.txt'
            model = Detector(pt_path, namesfile , 416, xcycwh=False) 这个bug就消失了，但是检测出的图片只有第一类，其他类都不会被检测出来，发现代码根本就不会读取classes.txt，但是去掉这句话就会出现如题一样的bug。
并且如果将 def __init__(self, pt_path, namesfile, img_size, conf_thres=0.4, iou_thres=0.3, classes=0, agnostic_nms=False,
                 xcycwh=True, device=0): 中的namesfile,与self.class_names = self.load_class_names(namesfile)去掉 即上面变成为
class Detector(object):
    def __init__(self, pt_path,  img_size, conf_thres=0.4, iou_thres=0.3, classes=0, agnostic_nms=False,
                 xcycwh=True, device=0):
        self.pt_path = pt_path
        self.img_size = img_size
        self.device = torch.device('cuda:{}'.format(device))
        self.model = self.load_model()
        self.conf_thres = conf_thres
        self.iou_thres = iou_thres
        self.classes = classes
        self.agnostic_nms = agnostic_nms
        self.xcycwh = xcycwh
下面变为model = Detector(pt_path,  416, xcycwh=False)，
代码依然能运行，但是结果和上面一样，只能检测到classes中的第一类。          
求解答！

**Comment by yl305237731** [comment]
@chennaikai11 路径的问题，我不太清楚呢，没有用Windows运行过。那个文件确实不读取也没有影响，我代码里面没有使用它。

**Comment by yl305237731** [comment]
@chennaikai11 类别的问题，debug一下看看 NMS 那块吧

**Comment by chennaikai11** [comment]
谢谢解答！类别的问题，实测将classes从0改为None就可以检测出所有类别了！



---Original---
From: ***@***.***&gt;
Date: Wed, Nov 3, 2021 10:55 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [yl305237731/flexible-yolov5] TypeError: expected str, bytes or os.PathLike object, not NoneType (Issue #54)




 
@chennaikai11 类别的问题，debug一下看看 NMS 那块吧
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
