### ISSUE TITLE
修改backbone之后，在第一次训练自己的数据时，YOLOv5如何设置才能不用加载权重文件？让他自己训练出一个全新的权重文件

### ISSUE THREAD

**Issue by 123-cq** [yl305237731/flexible-yolov5#55]

**Comment by yl305237731** [comment]
你好，所有提供预训练权重的backbone默认不会加载预训练权重，如果想要加载，需要在对应的 model_XXX.yaml 中的 backbone添加字段 pretrained=True. 所以不用担心  @123-cq

**Comment by 123-cq** [comment]
那如果是在原始的YOLOv5源码上，应该怎么操作才不会加载权重？您了解么？
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yl305237731/flexible-yolov5"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月10日(星期三) 中午11:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yl305237731/flexible-yolov5] 修改backbone之后，在第一次训练自己的数据时，YOLOv5如何设置才能不用加载权重文件？让他自己训练出一个全新的权重文件 (Issue #55)





 
你好，所有提供预训练权重的backbone默认不会加载预训练权重，如果想要加载，需要在对应的 model_XXX.yaml 中的 backbone添加字段 pretrained=True. 所以不用担心  @123-cq
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yl305237731** [comment]
@123-cq 如果backbone采用 yolov5 原始得话，我的这个代码由于改变yolov5的结构，所以无法加载原始yolov5 的权重，会从新训练的
