### ISSUE TITLE
您好，运行代码总是显示utils文件下的python文件无法调用，我应该怎样修改，才能使train.py运行

### ISSUE THREAD

**Issue by mllgblgsm** [yl305237731/flexible-yolov5#56]

**Comment by yl305237731** [comment]
@mllgblgsm 你是在哪个目录下运行的呢，在scripts 外运行，按照我给的命令就行，我一直都这样运行的。如果还不行，我再看看。

**Comment by sunshehai** [comment]
@yl305237731 您好，运行python scripts/train.py 后，提示No module named 'utils.general',试下直接run train.py后提示 No such file or directory:'requirements.txt' 。我想试下swin-transformer,但是不行，谢谢

**Comment by sunshehai** [comment]
跑yolov5源码程序没问题，各种包应该装了

**Comment by sunshehai** [comment]
我的是linux环境

**Comment by woozi1122** [comment]
> @yl305237731 您好，运行python scripts/train.py 后，提示No module named 'utils.general',试下直接run train.py后提示 No such file or directory:'requirements.txt' 。我想试下swin-transformer,但是不行，谢谢

**Comment by woozi1122** [comment]
您好，我报的错是ModuleNotFoundError: No module named 'torchvision.models.utils'，我已经install 了requiremen，这是为啥呢？

**Comment by sunshehai** [comment]
@woozi1122 您好，我也出现了No module named 'torchvision.models.utils'这个问题，请问您解决了吗

**Comment by woozi1122** [comment]
> @woozi1122 您好，我也出现了No module named 'torchvision.models.utils'这个问题，请问您解决了吗

我把报错的那一行注释掉了，因为我主要想看swin部分的，你可以参考一下

**Comment by sunshehai** [comment]
@woozi1122 您好，我也想看swin部分，能加下好友交流下呢，我的qq462279693,谢谢，注释掉后还有点其它问题

**Comment by sunshehai** [comment]
你好，之后您出现过 no such file or directory:’requirements.txt’吗



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: woozi1122 ***@***.***&gt;
发送时间: 2021年11月17日 13:18
收件人: yl305237731/flexible-yolov5 ***@***.***&gt;
抄送: sunshehai ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [yl305237731/flexible-yolov5] 您好，运行代码总是显示utils文件下的python文件无法调用，我应该怎样修改，才能使train.py运行 (Issue #56)





  
@woozi1122 您好，我也出现了No module named 'torchvision.models.utils'这个问题，请问您解决了吗
  
我把报错的那一行注释掉了，因为我主要想看swin部分的，你可以参考一下
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by woozi1122** [comment]
> 你好，之后您出现过 no such file or directory:’requirements.txt’吗 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: woozi1122 ***@***.***&gt; 发送时间: 2021年11月17日 13:18 收件人: yl305237731/flexible-yolov5 ***@***.***&gt; 抄送: sunshehai ***@***.***&gt;, Comment ***@***.***&gt; 主题: Re: [yl305237731/flexible-yolov5] 您好，运行代码总是显示utils文件下的python文件无法调用，我应该怎样修改，才能使train.py运行 (Issue #56) @woozi1122 您好，我也出现了No module named 'torchvision.models.utils'这个问题，请问您解决了吗 我把报错的那一行注释掉了，因为我主要想看swin部分的，你可以参考一下 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

没有，出现这个问题你看一下你的工作路径

**Comment by sunshehai** [comment]
@woozi1122 您好，工作路径哪里可能有点问题呢？刚刚百度下没找到，我之前用u版的YOLO源码能跑通，路径和之前差不多，但是不知道为什么这个代码有问题，谢谢您的回答

**Comment by woozi1122** [comment]
> @woozi1122 您好，工作路径哪里可能有点问题呢？刚刚百度下没找到，我之前用u版的YOLO源码能跑通，路径和之前差不多，但是不知道为什么这个代码有问题，谢谢您的回答

不是，你执行的时候先cd 到requirement所在的文件夹下试试看，比如这个文件就是要cd到flexible-yolov5下。

**Comment by sunshehai** [comment]
@woozi1122  1.只能python scripts/train.py可以跑通，run train.py不能跑通，不知道您是不是这种情况？我觉得是requirements.txt和train.py不在同一目录下,但把他们放在同一目录又出现其他问题，可能还得需要改其他地方。2.请问下您把swin当作backbone后效果比原始yolo效果怎么样呢？我之后试试我的数据集跑一下。最后非常感谢您的帮助

**Comment by woozi1122** [comment]
> @woozi1122 1.只能python scripts/train.py可以跑通，run train.py不能跑通，不知道您是不是这种情况？我觉得是requirements.txt和train.py不在同一目录下,但把他们放在同一目录又出现其他问题，可能还得需要改其他地方。2.请问下您把swin当作backbone后效果比原始yolo效果怎么样呢？我之后试试我的数据集跑一下。最后非常感谢您的帮助

我执行的就是python scripts/train.py,跑通了就没有再管了，我也是个学习者，看看后续有时间的话再改。没有帮上你的忙非常抱歉。

**Comment by sunshehai** [comment]
帮了我很大忙，非常感谢您
