### ISSUE TITLE
训练过程中召回率和精度、mAP过低

### ISSUE THREAD

**Issue by NiWeInIwEi** [yl305237731/flexible-yolov5#57]
数据集是VOC2028安全帽那个的前1600张图片，用transform_voc.py准备数据，将labels和images放在项目工程同一级文件夹datasets下
选择的是mobilenet，data.yaml和model_mobilenet.yaml都按要求做了修改
precision和recall不超过0.05，mAP50不超过0.01
训练过程中置obj-loss一直不收敛，甚至在稳定增加

**Comment by Him-wen** [comment]
hi，你是换的哪个backbone？

**Comment by NiWeInIwEi** [comment]
readme.markdown里面的都试了，感觉像是一直在局部最优解徘徊


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: Himwen_ ***@***.***&gt;
发送时间: 2021年11月27日 22:37
收件人: yl305237731/flexible-yolov5 ***@***.***&gt;
抄送: NiWeInIwEi ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[yl305237731/flexible-yolov5] 训练过程中召回率和精度、mAP过低 (Issue #57)





 
hi，你是换的哪个backbone？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yl305237731** [comment]
我有空下载这个数据集试试

**Comment by yl305237731** [comment]
@NiWeInIwEi 我用VOC2028 测试了一下，用的全量数据。yolov5s batch-size=16 只训练了12轮的测试结果，这么看来模型是没有问题的，可能是数据分布或者数据量问题？
![image](https://user-images.githubusercontent.com/9928596/144014975-1ba95384-b1fd-40ef-8189-3ce64b4dfa99.png), 等会儿我再测mobilenet small 的结果

**Comment by yl305237731** [comment]
mobilenet small 15 epoch 
![image](https://user-images.githubusercontent.com/9928596/144023495-862ed01c-1f01-4aa5-8225-ab69ad39f2e0.png)

**Comment by yl305237731** [comment]
@NiWeInIwEi  模型没有问题
