### ISSUE TITLE
添加别的backbone

### ISSUE THREAD

**Issue by chennaikai11** [yl305237731/flexible-yolov5#58]
您好，请问如果想像您这样添加其他的主干网络，需要怎么做呢？是不是首先在bakebone文件夹下写好网络，然后把新写的类添加进到common.py中就行了？

**Comment by yl305237731** [comment]
@chennaikai11 修好网络文件，网络输出三层（目前只支持标准的三层输出，也可以输出更多层，但你得改一些代码），网络里面需要 `self.out_shape` = {'C3_size': self.channels_out['stage3_2'],
                          'C4_size': self.channels_out['stage4_2'],
                          'C5_size': self.channels_out['conv1']}`， 会将每一层输出的通道数带到neck 里面。然后在models/backbone/__init__.py 导入即可

**Comment by chennaikai11** [comment]
好的，还有个问题想请教一下，我想把mobilenetv3中的se注意力机制替换成其他注意力机制，是先定义一个其余的attention的类然后把Bottleneck Residual Block中的se替换成新定义的注意力，就行了吗。

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月29日(周一) 下午5:34
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [yl305237731/flexible-yolov5] 添加别的backbone (Issue #58)




 
@chennaikai11 修好网络文件，网络输出三层（目前只支持标准的三层输出，也可以输出更多层，但你得改一些代码），网络里面需要 self.out_shape = {'C3_size': self.channels_out['stage3_2'],
 'C4_size': self.channels_out['stage4_2'],
 'C5_size': self.channels_out['conv1']}`， 会将每一层输出的通道数带到neck 里面。然后在models/backbone/init.py 导入即可
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yl305237731** [comment]
@chennaikai11 是的

**Comment by chennaikai11** [comment]
感谢指点，应该成功了
