### ISSUE TITLE
error with train.py

### ISSUE THREAD

**Issue by thomas9574** [yl305237731/flexible-yolov5#59]
i tried to launch for training 
!python scripts/train.py --img 800 --batch 16 --epochs 20   --data '../data.yaml' --cfg ./configs/model_yolo.yaml 

But got the error
 Traceback (most recent call last):
  File "scripts/train.py", line 527, in <module>
    train(hyp, opt, device, tb_writer, wandb)
  File "scripts/train.py", line 87, in train
    model = Model(opt.cfg).to(device)  # create
  File "./od/models/model.py", line 22, in __init__
    model_config = yaml.load(open(model_config, 'r'))
TypeError: load() missing 1 required positional argument: 'Loader'
The model i chose is model_yolo.yaml.
Can u please tell me what's wrong?

**Comment by a227799770055** [comment]
@thomas9574 
Hi, I meet the same problem with you, and just rewrite the code "yaml.load(open(model_config, 'r'))
" to yaml.full_load(open(model_config, 'r')) can solved the problem.

ref: https://stackoverflow.com/questions/69564817/typeerror-load-missing-1-required-positional-argument-loader-in-google-col
