### ISSUE TITLE
Autosplit: How can I shuffle img before split it directly ?  I am concerned without shuffle would lead to distribution bias in train/val

### ISSUE THREAD

**Issue by ShirleyHe2020** [yl305237731/flexible-yolov5#6]
def autosplit(path='../coco128', weights=(0.9, 0.1, 0.0)):  # from utils.datasets import *; autosplit('../coco128')
    """ Autosplit a dataset into train/val/test splits and save path/autosplit_*.txt files
    # Arguments
        path:       Path to images directory
        weights:    Train, val, test weights (list)
    """
    path = Path(path)  # images dir
    files = list(path.rglob('*.*'))
    n = len(files)  # number of files
    indices = random.choices([0, 1, 2], weights=weights, k=n)  # assign each image to a split
    txt = ['autosplit_train.txt', 'autosplit_val.txt', 'autosplit_test.txt']  # 3 txt files
    [(path / x).unlink() for x in txt if (path / x).exists()]  # remove existing
    for i, img in tqdm(zip(indices, files), total=n):
        if img.suffix[1:] in img_formats:
            with open(path / txt[i], 'a') as f:
                f.write(str(img) + '\n')  # add image to txt file

**Comment by yl305237731** [comment]
did you mean this ：random.shuffle(files) ?

**Comment by ShirleyHe2020** [comment]
> did you mean this ：random.shuffle(files) ?

yes, wanna shuffle the dataset before splitting if into train/val/test.
