### ISSUE TITLE
Validation dataset output image size not match the setting value?

### ISSUE THREAD

**Issue by a227799770055** [yl305237731/flexible-yolov5#61]
Hi, @yl305237731 
I want to ask that I just setting the "--img-size" of train and test as [480, 480] at train.py. However, I got the test image size not match the which I setted. I think the problem may caused by the function ''create_dataloader'', bit I don't know how to fix it.

**Comment by yl305237731** [comment]
@a227799770055 you can find the explain in  https://github.com/ultralytics/yolov5/issues/4191。for your needs, you can set rect=False in line 198 of scripts/train.py. Then the test image size will be 480 * 480.
