### ISSUE TITLE
关于cbam的提升

### ISSUE THREAD

**Issue by achel-x** [yl305237731/flexible-yolov5#63]
您好，我看见你的主页上说这个repo有实现cbam的部分，但是我很好奇，关于CBAM对yolo的提升大概是多少呢

**Comment by yl305237731** [comment]
@achel-x由于我之前只实现了，并没有完全进行验证，所以效果不太好说。我最近正在一个一个训练。

**Comment by achel-x** [comment]
@yl305237731 感谢回复，我用u版6.0的代码，训练的是yolov3.yaml来添加cbam。
结果不是很理想，在VOC数据集上，使用提供的yolov3.pt作为初始化模型，imgsz为416，不加cbam的情况下，mAP约为83.2左右，而加入cbam以后mAP反而下降至82.9，略微下降了，我看yolov4中仅适用了cbam中的sam部分，大约比不添加提升了0.4（在yolov4 的 model zoo中），所以非常奇怪。
如果您做到这部分的时候，希望能和我交流一下。

**Comment by achel-x** [comment]
我也尝试把channel attention去掉，前期会上升的比较快，但是进入收敛阶段反而下降的更多，即只使用sam时，效果低于82.9，大约在82.5左右

**Comment by yl305237731** [comment]
@achel-x ok
