### ISSUE TITLE
VGG16 backbone

### ISSUE THREAD

**Issue by myasser63** [yl305237731/flexible-yolov5#65]
I am trying to use VGG16 as backbone but i couldn't make it to work. Can you help to add VGG as backbone

**Comment by yl305237731** [comment]
@myasser63 ok

**Comment by yl305237731** [comment]
@myasser63 Done!

**Comment by myasser63** [comment]
Thanks alot for your quick response. Can you please give me a guide on references to learn to do such modifications

**Comment by yl305237731** [comment]
@myasser63  
1. you  can find an open source model code directly,
2. return the features of the last three stages in the forward function, in this step, You may need to modify the network
3. you need add  self.out_shape = {'C3_size': out_channels3, 'C4_size': out_channels4, 'C5_size': out_channels5}  in model class.

**Comment by myasser63** [comment]
Thanks for the explanation.

Should I use --weights' ' or yolov5s.pt to train with different backbone?

**Comment by yl305237731** [comment]
> Thanks for the explanation.
> 
> Should I use --weights' ' or yolov5s.pt to train with different backbone?

@myasser63 sorry, you can't

**Comment by myasser63** [comment]
Do you mean I can't use `--weights` argument? Even best.pt?

**Comment by yl305237731** [comment]
@myasser63 If you change the backbone, you can't load the trained weight of another backbone.

**Comment by myasser63** [comment]
Do you have any idea if mi want to use two backbones what changes should be done?

**Comment by yl305237731** [comment]
@myasser63 use two backbone? what's mean?

**Comment by myasser63** [comment]
I want to try using two parallel backbone models.

**Comment by yl305237731** [comment]
Oh, the idea is very novel and needs to be changed a lot

**Comment by myasser63** [comment]
I have a probelm to find out how to split the input into branches
