### ISSUE TITLE
Update to latest YOLOv5 v6.0

### ISSUE THREAD

**Issue by myasser63** [yl305237731/flexible-yolov5#67]
Hi, Can you please updae the network archeticture for yolov5 head nad backbone to match the latest version.

**Comment by yl305237731** [comment]
ok, Maybe it will be updated later😂

**Comment by myasser63** [comment]
Could you provide assistance to learn how to build my own SSD object detection model. I am doing masters and I can't find a good reference to do that

**Comment by LinB203** [comment]
同，我也希望更新yolov5 6.1
