### ISSUE TITLE
In FPN, yolo version can't change

### ISSUE THREAD

**Issue by songyangsun** [yl305237731/flexible-yolov5#68]
od/models/model.py

![1](https://user-images.githubusercontent.com/23733567/148762148-9c326e97-efb2-40de-80de-6e963c2f3ef4.png)

od/models/neck/FPN.py

![2](https://user-images.githubusercontent.com/23733567/148762212-049bd5f0-0f29-4d6a-925e-cf3ffeea17cc.png)

I test it by using print('FPN version:', version) in FPN.py.When i use 'm' version in configs/model_yolo.yaml,i get version is 'S' by print() instead.

**Comment by yl305237731** [comment]
@songyangsun OK，i will test it

**Comment by yl305237731** [comment]
@songyangsun done
