### ISSUE TITLE
Low Accuracy

### ISSUE THREAD

**Issue by AbhiroopBhattacharya** [yl305237731/flexible-yolov5#69]
Hello! 
Thank you for sharing the repo. I have run experiments to compare the results from the Ultralytics YOLOv5s implementation and the model_yolo.yaml with version 's' . However, I am getting a much lower accuracy for this implementation. Is there some pre-processing step which I have missed? Thanks

**Comment by yl305237731** [comment]
@AbhiroopBhattacharya https://github.com/yl305237731/flexible-yolov5/issues/16    may be you meet same error?

**Comment by AbhiroopBhattacharya** [comment]
No I have changed the number of classes as per the dataset. I have also made the following changes:
1. Changed  "from torchvision.model.utils import  import load_state_dict_from_url"  to. "from torch.hub import load_state_dict_from_url" as the new version of Pytorch does not support the earlier one.
2. Added a Loader=yaml.SafeLoader in od/models/models.py line 22.
3. If running model_resnet the FPN does not accept the version as 50 thus manually changed it to 's'
I am unable to get the correct results. Anything else which I might be missing? (screenshot attached for ResNet50)

Thanks
![Screenshot 2022-01-17 at 9 50 51 AM](https://user-images.githubusercontent.com/77635204/149791336-04bc3681-8e4e-451c-9145-e9b91fb06ecb.png)

**Comment by AbhiroopBhattacharya** [comment]
Also, when I am trying to use the "yolo5s.pt" weights . I get the following error. Any idea what might be causing the error? Thanks

Namespace(adam=False, batch_size=16, bucket='', cache_images=False, cfg='./configs/model_yolo.yaml', data='./configs/data.yaml', device='', epochs=50, evolve=False, exist_ok=False, global_rank=-1, hyp='configs/hyp.scratch.yaml', image_weights=False, img_size=[640, 640], linear_lr=False, local_rank=-1, log_artifacts=False, log_imgs=16, multi_scale=False, name='exp', noautoanchor=False, nosave=False, notest=False, project='runs/train', quad=False, rect=False, resume=False, save_dir='runs/train/exp6', single_cls=False, sync_bn=False, total_batch_size=16, weights='/content/flexible-yolov5/yolov5s.pt', workers=8, world_size=1)
Start Tensorboard with "tensorboard --logdir runs/train", view at http://localhost:6006/
hyperparameters: lr0=0.01, lrf=0.2, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=0.05, cls=0.5, cls_pw=1.0, obj=1.0, obj_pw=1.0, iou_t=0.2, anchor_t=4.0, fl_gamma=0.0, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0
Traceback (most recent call last):
  File "scripts/train.py", line 527, in <module>
    train(hyp, opt, device, tb_writer, wandb)
  File "scripts/train.py", line 77, in train
    ckpt = torch.load(weights, map_location=device)  # load checkpoint
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 607, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 882, in _load
    result = unpickler.load()
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 875, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'models'

**Comment by yl305237731** [comment]
@AbhiroopBhattacharya for your low acc problem, I can't find any problems. I completely retrained not use pretrained weights , but didn't have such problems
