### ISSUE TITLE
Why do we need to remove batchnorm after fuse? 

### ISSUE THREAD

**Issue by ShirleyHe2020** [yl305237731/flexible-yolov5#7]
def fuse(self):  # fuse model Conv2d() + BatchNorm2d() layers
        print('Fusing layers... ')
        for module in [self.backbone, self.fpn, self.pan, self.detection]:
            for m in module.modules():
                if type(m) is Conv and hasattr(m, 'bn'):
                    m.conv = fuse_conv_and_bn(m.conv, m.bn)  # update conv
                    delattr(m, 'bn')  # remove batchnorm
                    m.forward = m.fuseforward  # update forward
        self.info()
        return self
-------------------------------------------------------------------
delattr(m, 'bn')  # remove batchnorm  can you please help explain why it's necessary to remove batchnorm here?

**Comment by yl305237731** [comment]
@ShirleyHe2020   In order to speed up  inference, conv and BN need to be fused together. After fusion, conv has changed, including BN operation, so the original BN is not needed, Please refer to: https://tehnokv.com/posts/fusing-batchnorm-and-conv/
