### ISSUE TITLE
backbone,FPN and PAN is not clear,need to refactor

### ISSUE THREAD

**Issue by songyangsun** [yl305237731/flexible-yolov5#70]
backbone:
![1](https://user-images.githubusercontent.com/23733567/149740133-7776c0a3-6744-45d0-a375-22b0e91cdef7.jpg)

FPN and PAN:
![5](https://user-images.githubusercontent.com/23733567/149740180-d3c1730b-18a3-4e0f-9118-5b0aa40b4619.png)

you can compare with code,such as

in od/models/backbone/yolov5.py 
![102](https://user-images.githubusercontent.com/23733567/149740697-da422d7e-683b-4d29-b39b-90b2296948e2.jpg)

another i found is behind P3, after concat(), that C3 module should be in FPN instead of PAN.

i found two places,refactoring is a little dull,but i think it's clearer and easier for user to understand and use.

**Comment by yl305237731** [comment]
@songyangsun thanks

**Comment by songyangsun** [comment]
This is my changes,you can refer it.There are some code comments from me,you can clean them or give you some help maybe.

I use this way instead of PR because i can't use git of github easily,hope it can make sense.

[给yolo的PR.zip](https://github.com/yl305237731/flexible-yolov5/files/7897688/yolo.PR.zip)

**Comment by yl305237731** [comment]
@songyangsun OK，thanks
