### ISSUE TITLE
how to add dropblock

### ISSUE THREAD

**Issue by songyangsun** [yl305237731/flexible-yolov5#71]
dropblock is mentioned in yolov4 paper,but many repo don't add it.So i wanna know how to add dropblock and where should it be added?

**Comment by yl305237731** [comment]
@songyangsun for dropblock, i refer to ppyolov1, they add dropblock in FPN. you can refer it.

**Comment by songyangsun** [comment]
@yl305237731 the ppyolov1 you have mentioned,does it have pytorch version implement?or can you share the detailed link(url) with me?
thanks!

**Comment by yl305237731** [comment]
@songyangsun https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/ppdet/modeling/necks/yolo_fpn.py

**Comment by songyangsun** [comment]
@yl305237731 thanks
