### ISSUE TITLE
Does it can support backbone of ppyolov2? which called ResNet50vd-DCN

### ISSUE THREAD

**Issue by songyangsun** [yl305237731/flexible-yolov5#72]
i see many repo with .cfg only,without detailed implements of backbone,such as od/models/backbone/yolov5.py.So i hope this repo can support it.

**Comment by yl305237731** [comment]
@songyangsun ok, i will try it, or you can  try to modify and PR.☹️🤒💪

**Comment by songyangsun** [comment]
@yl305237731 got it.
