### ISSUE TITLE
torchsummary使用问题

### ISSUE THREAD

**Issue by jkkkc** [yl305237731/flexible-yolov5#73]
你好，我使用torchsummary打印输出 ./od/models/model.py时报错AttributeError: 'int' object has no attribute 'size'.模型载入的是model_swim模型，请问这个问题怎么解决呢？

**Comment by yl305237731** [comment]
有空我看看

**Comment by yl305237731** [comment]
@jkkkc sorry, can't use torchsummary to print model,
