### ISSUE TITLE
將模型載入為 FP16?

### ISSUE THREAD

**Issue by a227799770055** [yl305237731/flexible-yolov5#77]
想要請問原本的 model loading 進來時為 FP32 的格式
有辦法藉由修改哪個部份將 model 載入為 FP16嗎?

**Comment by yl305237731** [comment]
model.half()  @a227799770055

**Comment by yl305237731** [comment]
不对，这么加载进来的也是32的

**Comment by a227799770055** [comment]
那有什麼辦法可以將model 轉為 tensorRT的格式嘛？因為想要加速model的速度

**Comment by yl305237731** [comment]
@a227799770055 仓库里面有转trt的代码

**Comment by yl305237731** [comment]
https://github.com/yl305237731/flexible-yolov5/tree/main/scripts/trt_quant

**Comment by a227799770055** [comment]
@yl305237731  請問它只能從 onnx 轉嘛？ 還是可以由 pt檔轉換？
謝謝！！

**Comment by yl305237731** [comment]
这个代码得先转onnx
