### ISSUE TITLE
Convert onnx to trt error

### ISSUE THREAD

**Issue by a227799770055** [yl305237731/flexible-yolov5#78]
想要請問一下 我在將 onnx 轉換為 tensonrt 的權重檔時，出現了下方的錯誤訊息。
想請問是否有人有遇過該情形，且如何解決。
謝謝！！

`[TensorRT] ERROR: Network must have at least one output
[TensorRT] ERROR: Network validation failed.
Failed to create the engine
Traceback (most recent call last):
  File "/home/insign/Doc/insign/flexible-yolov5/scripts/trt_quant/convert_trt_quant.py", line 93, in <module>
    assert engine_fixed, 'Broken engine_fixed'
AssertionError: Broken engine_fixed`

**Comment by yl305237731** [comment]
你导出 onnx 的时候输出层有做过什么操作吗

**Comment by a227799770055** [comment]
沒有，我直接執行 scripts/deploy/export.py 的檔案

**Comment by moontsar** [comment]
same problem. And I set model.detection.export = True, it works.

**Comment by yl305237731** [comment]
README 里面deploy写了官方tensorrt 时需要作的操作

**Comment by a227799770055** [comment]
因為我模型的 backbone 有自己修改過，我發現在 pt 檔 轉換為 onnx 的過程中出現了下面的 warning，但最後還是有轉換成功。
想請問有遇過這樣的狀況嘛？
謝謝！！
`Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied.`

**Comment by yl305237731** [comment]
@a227799770055 每遇到过，不过一般warning 都问题不大

**Comment by a227799770055** [comment]
了解，感謝！

**Comment by a227799770055** [comment]
@moontsar  I have tried the way you suggest, but the result also show the same error.
