### ISSUE TITLE
ValueError in train.py

### ISSUE THREAD

**Issue by anidh** [yl305237731/flexible-yolov5#79]
Hi There, Thanks for the amazing work. I tried running the train.py script using the command
`
python scripts/train.py  --batch 16 --epochs 5 --data configs/data.yaml --cfg configs/model_resnet.yaml --device 0`

but I'm getting an error 
```

Traceback (most recent call last):
  File "scripts/train.py", line 527, in <module>
    train(hyp, opt, device, tb_writer, wandb)
  File "scripts/train.py", line 190, in train
    mlc = np.concatenate(dataset.labels, 0)[:, 0].max()  # max label class
  File "/home/anidh/fyolo/lib/python3.8/site-packages/numpy/core/_methods.py", line 40, in _amax
    return umr_maximum(a, axis, None, out, keepdims, initial, where)
ValueError: zero-size array to reduction operation maximum which has no identity
```
This error was also reported on the ultralytics repo on this [link](https://github.com/ultralytics/yolov5/issues/1544) for which a PR was suggested but when I looked at the file the PR changes were already there. So I'm not sure what's causing this error.
Also, this same command starts the training without any issues on the ultralytic's Yolov5 repo.

Thanks for helping out with the issue.

**Comment by yl305237731** [comment]
@anidh sorry, I train model so many time, never meet this issue. may be caused by env?
