### ISSUE TITLE
How to replace yolo backbone with mobilenet3 ? 

### ISSUE THREAD

**Issue by ShirleyHe2020** [yl305237731/flexible-yolov5#8]
Hi, can you please kindly tell how to assign a specific backbone (eg: mobilenet3) to model ? 
Have read models.py under  /od/ , still no idea how to assign it? 

model.py , train.py , or __init__.py under /backbone, which one need to be modified when try to train?

**Comment by yl305237731** [comment]
@ShirleyHe2020 

choose backbone by  --cfg
I give some template configs in configs/

for mobilenet  :  python scripts/train.py  --batch 16 --epochs 5 --data configs/data.yaml --cfg confgis/model_mobilenet.yaml
for resnet: python scripts/train.py  --batch 16 --epochs 5 --data configs/data.yaml --cfg confgis/model_resnet.yaml

**Comment by yl305237731** [comment]
so give me a star...

**Comment by ShirleyHe2020** [comment]
> so give me a star...

sure, done !

**Comment by ShirleyHe2020** [comment]
> @ShirleyHe2020
> 
> choose backbone by --cfg
> I give some template configs in configs/
> 
> for mobilenet : python scripts/train.py --batch 16 --epochs 5 --data configs/data.yaml --cfg confgis/model_mobilenet.yaml
> for resnet: python scripts/train.py --batch 16 --epochs 5 --data configs/data.yaml --cfg confgis/model_resnet.yaml

what if I want to choose a specific backbone version,  ie.  there are multiple versions in resnet(18,34, 50,101, 152 ) , How can I add **kwargs to  python scripts/train.py --batch 16 --epochs 5 --data configs/data.yaml --cfg confgis/model_resnet.yaml
so that I can compare resnet50 and resnet101

**Comment by yl305237731** [comment]
@ShirleyHe2020 in configs/model_resnet.yaml, change version to whatever you want. the default resnet version is 50

**Comment by ShirleyHe2020** [comment]
> @ShirleyHe2020 in configs/model_resnet.yaml, change version to whatever you want. the default resnet version is 50

After  I set version to small (default value is large) in confgis/model_mobilenet.yaml,  I got multiple  error messages when tried to train : 
=====================================================================
/home/qian/anaconda3/envs/ultra_YOLOv5/flexible-yolov5-main/od/models/model.py:22: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  model_config = yaml.load(open(model_config, 'r'))
Traceback (most recent call last):
  File "train.py", line 527, in <module>
    train(hyp, opt, device, tb_writer, wandb)
  File "train.py", line 87, in train
    model = Model(opt.cfg).to(device)  # create
  File "/home/user/anaconda3/envs/ultra_YOLOv5/flexible-yolov5-main/od/models/model.py", line 25, in __init__
    self.backbone = build_backbone(backbone_type, **model_config.backbone)
  File "/home/user/anaconda3/envs/ultra_YOLOv5/flexible-yolov5-main/od/models/backbone/__init__.py", line 16, in build_backbone
    backbone = eval(backbone_name)(**kwargs)
  File "/home/user/anaconda3/envs/ultra_YOLOv5/flexible-yolov5-main/od/models/backbone/mobilenetv3.py", line 196, in __init__
    'C5_size': self.out_channels[3]}
IndexError: list index out of range
-

**Comment by yl305237731** [comment]
@ShirleyHe2020 My fault, I only tested large. Small does have this bug. I'll change it tomorrow

**Comment by yl305237731** [comment]
fix this bug
