### ISSUE TITLE
inference / detection on unseen image

### ISSUE THREAD

**Issue by markanethio** [yl305237731/flexible-yolov5#80]
Thank you for the great work. I have been trying to run the detector.py script using the command
!python scripts/detector.py 

but, the code doesn't have a similar structure to the original yolov5 which can be run by using the command
!python detect.py --weights /content/yolov5/runs/train/exp/weights/last.pt --img 256  --source /content/drive/MyDrive/data/test/images --save-txt --save-conf

Could you please give an example of how to run the detector? scripts/detector

**Comment by yl305237731** [comment]
@efremobsie this is a simple detector script, it's not like train or eval command, you can just modify follow code

`
    pt_path = 'your  model.pt path'    
    model = Detector(pt_path, None, 640, xcycwh=False)
    imgs_root = 'your test images dir '
    imgs = os.listdir(imgs_root)
    save_dir = 'save vis image dir'

` 

Or you can rewrite this code as  "!python detect.py --weights /content/yolov5/runs/train/exp/weights/last.pt --img 256 --source /content/drive/MyDrive/data/test/images --save-txt --save-conf"  style.

**Comment by efremobsie** [comment]
## inference or detection on new images
**First I modified the pt_path and imgs_root and save_dir as shown below.**
    pt_path = '/content/flexible-yolov5/runs/train/exp5/weights/best.pt'
    model = Detector(pt_path, None, 256, xcycwh=False)
    imgs_root = '/content/VOCdevkit/images/val'
    imgs = os.listdir(imgs_root)
    save_dir = '/content/flexible-yolov5/runs/detect'

**Then I run the below codes**
!python /content/flexible-yolov5/scripts/detector.py --weights /content/flexible-yolov5/runs/train/exp5/weights/best.pt --img 256 --source /content/VOCdevkit/images/val --save-txt --save-conf

**But, I got the below error in the process of detection**
Fusing layers... 
/usr/local/lib/python3.7/dist-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Traceback (most recent call last):
  File "/content/flexible-yolov5/scripts/detector.py", line 131, in <module>
    model = Detector(pt_path, None, 256, xcycwh=False)
  File "/content/flexible-yolov5/scripts/detector.py", line 23, in __init__
    self.class_names = self.load_class_names(namesfile)
  File "/content/flexible-yolov5/scripts/detector.py", line 30, in load_class_names
    with open(namesfile, 'r', encoding='utf8') as fp:
TypeError: expected str, bytes or os.PathLike object, not NoneType

_**please, I need your help !!!**_

**Comment by yl305237731** [comment]
@markanethio use latest code, I modify it

**Comment by yl305237731** [comment]
@markanethio and for this script, you don't need run like "!python /content/flexible-yolov5/scripts/detector.py --weights /content/flexible-yolov5/runs/train/exp5/weights/best.pt --img 256 --source /content/VOCdevkit/images/val --save-txt --save-conf",

just python scripts/detector.py

**Comment by markanethio** [comment]
Thank you, working perfect
