### ISSUE TITLE
加载作者提供的resnet-18.pt出错

### ISSUE THREAD

**Issue by amoursm** [yl305237731/flexible-yolov5#83]
``我改了data.yaml里的nc，只有1类，resnet.yaml也改过了，最开始使用原代码跑的时候报错说权重和网络维度不匹配，后来我在加载时加了个判断：        for key, value in original_dict.items():
            for key2, value2 in state_dict.items():
                if value2.size() == value.size():
                    original_dict[key] = state_dict[key2]`
`还是报错如下：RuntimeError: The size of tensor a (255) must match the size of tensor b (18) at non-singleton dimension 0`
请问是什么原因呢？感觉还是跟预测类别有关，255=（80+5）*3, 18=(1+5)*3

**Comment by yl305237731** [comment]
@amoursm  不好意思，在上传完这些权重后，我又改了模型的配置，导致参数对不上了，所以没法加载了，目前只可以做个性能对比了
