### ISSUE TITLE
size mismatch for fpn?

### ISSUE THREAD

**Issue by HuKai-cv** [yl305237731/flexible-yolov5#84]
![image](https://user-images.githubusercontent.com/68494594/160334321-f3dd13cb-0e2c-4e67-aad8-372000a934ff.png)

**Comment by yl305237731** [comment]
@SCAU-HuKai Sorry, after uploading these weights, I changed the configuration of the model, resulting in the mismatch of parameters, so can't load it. At present, can only make a performance comparison

**Comment by hlyzzr** [comment]
请问这要怎么解决呢？

**Comment by Bobo-y** [comment]
@hlyzzr 现在还不能吗，已经重新上传了

**Comment by hlyzzr** [comment]
> @hlyzzr 现在还不能吗，已经重新上传了

使用预训练权重还是会报这个错
