### ISSUE TITLE
是否没有加载预训练模型？

### ISSUE THREAD

**Issue by Liqq1** [yl305237731/flexible-yolov5#87]
您好！请问您的代码是否没有加载预训练模型？我在调用resnet50作为backbone的时候，指标变动有点奇怪
<img width="1311" alt="image" src="https://user-images.githubusercontent.com/54054113/161430216-5447669e-21ec-4aa4-928c-2ad43bbcb04f.png">

**Comment by yl305237731** [comment]
@Liqq1    在model_resnet.yaml 里面，加上
`backbone:
  type: resnet
  version: '50'  # 18, 34, 50, 101, 152
  dcn: False
  cbam: False
  pretrained: True
`
如果backbone支持加载预训练，加上这个就行。

**Comment by Liqq1** [comment]
> @Liqq1 在model_resnet.yaml 里面，加上
> `backbone: type: resnet version: '50' # 18, 34, 50, 101, 152 dcn: False cbam: False pretrained: True `
> 如果backbone支持加载预训练，加上这个就行。

感谢回复，另外我想问一下对于model_yolo.yaml我想添加预训练模型该如何操作呢？好像不可以直接在其中添加pretrained: True

**Comment by yl305237731** [comment]
@Liqq1 yolo 加载不了预训练模型

**Comment by Liqq1** [comment]
> @Liqq1 yolo 加载不了预训练模型

YOLOv5的源码中是可以提前加载整个预训练模型的，这边加载不了是因为没有写进去吗？

**Comment by yl305237731** [comment]
@Liqq1 因为结构发生了变化，所以没法加载原作者的预训练权重。我自己上传的预训练权重现在也不能加载了，因为我又改了网络结构
